#!/usr/bin/env perl

use Mojolicious::Lite;

get '/' => sub {
  
    my $self = shift;  
    $self->render('intro', layout => 'default');

} => 'intro';

get '/comments' => sub {
  
    my $self = shift;  
    $self->render('comments', layout => 'default');

} => 'comments';

app->config(hypnotoad => {proxy => 1, listen => ['http://*:2099']});
app->start;
